### ISSUE TITLE
Improve Ontology of OR

### ISSUE THREAD

**Issue by WolfgangFahl** [SmartDataAnalytics/OpenResearch#103]
see https://github.com/SmartDataAnalytics/OpenResearch/blob/master/code/ontology/openresearch.ttl

**Comment by WolfgangFahl** [comment]
or shall we completely remove the legacy reference?

**Comment by StroemPhi** [comment]
@WolfgangFahl I think it is best to only link to the repository in which AEON is developed, which is here: https://github.com/tibonto/aeon

**Comment by WolfgangFahl** [comment]
That is already in https://github.com/SmartDataAnalytics/OpenResearch/blob/master/README.md
