### ISSUE TITLE
Change of property datatype shows no effect

### ISSUE THREAD

**Issue by tholzheim** [SmartDataAnalytics/OpenResearch#131]
I changed the datatype of an property but when the value is queried it is still returned in the old format.
>See https://confident.dbis.rwth-aachen.de/orth/index.php?title=Property:Event_id
I changed the datatype of the property placeholder from page to text. In the template representation the value is shown correctly as text but if queried with {{#show ...}} it is shown as page link

**Comment by WolfgangFahl** [comment]
As similar issues was solved by me with the workaround in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4923

**Comment by WolfgangFahl** [comment]
Rebooting fixed the issue.
