### ISSUE TITLE
Align GitHub issue tracker with TODO list

### ISSUE THREAD

**Issue by clange** [SmartDataAnalytics/OpenResearch#14]
I see that (probably before setting up this GitHub project) we also had https://www.openresearch.org/wiki/Openresearch:TODO. It would be a good idea to turn the remaining TODOs there into issues here, or at the very least to link from the TODO page to this issue tracker, saying that from now onwards new issues should be reported here.

**Comment by WolfgangFahl** [comment]
1. #90
2. #91 
3. #92
