### ISSUE TITLE
Add Object Oriented python access to Event, EventSeries and other relevant Entities/Topics

### ISSUE THREAD

**Issue by WolfgangFahl** [SmartDataAnalytics/OpenResearch#155]
To better  support the migration we should be able handle the main content elements of OpenResearch in an object oriented way. 

For a start the representation change code according to the QUASAR blood group approach should be handled so that later the objects/classes can be reused to implement #70

**Comment by MusaabKh** [comment]
Event could rate themselves e.g having duplicates or having the wrong Ordinal

**Comment by tholzheim** [comment]
Should the data be queried directly from OPENRESEARCH or cached to be more responsive?

**Comment by WolfgangFahl** [comment]
A frontend like https://confident.dbis.rwth-aachen.de/dblpconf/ would need a cached version e.g. in sqlite, json, a graph database or the like. I'd recommend to simply start with the pyLodStorage List of Dicts approach. We have to options to create a list of dicts and persist it - one is to use an SMW Query like the PTP parser does - the other is to parse the .wiki files as is already done in wikiextract. The Current code of event.py is a starting point for this route. Please note that the CI environment has the nightly backup available already!

**Comment by WolfgangFahl** [comment]
Events should have a list of problems attached to them. Each problem should have a rating e.g. severity and whether it needs automation.

**Comment by WolfgangFahl** [comment]
Working on the frontend needs online sessions where we code together (hackathon ...)

**Comment by tholzheim** [comment]
event and event series should be available as python list of dicts derived from wikiquery or wiki-markup files (from wikibackup)

**Comment by WolfgangFahl** [comment]
This works in principle now. Let's open specific issues for further improvements.

**Comment by WolfgangFahl** [comment]
Type handling needs to be fixed e.g. for ordinal

**Comment by WolfgangFahl** [comment]
No issue here any more it is an issue of ConferenceCorpus
