### ISSUE TITLE
Import of css gives warnings

### ISSUE THREAD

**Issue by tholzheim** [SmartDataAnalytics/OpenResearch#159]
See [MediaWiki:Common.css](https://www.openresearch.org/mediawiki/index.php?title=MediaWiki:Common.css&action=history)
```
@import "http://webfonts.ru/import/ptsans.css";
```

**Comment by WolfgangFahl** [comment]
Since the link is broken anyway it does not have any effect at this time. Probably the intention was to use the font:

https://www.cssfontstack.com/PT-Sans
And thats a matter of how things look. We might use a different font and avoid the import by cut&paste
