### ISSUE TITLE
Duplicate acronyms

### ISSUE THREAD

**Issue by WolfgangFahl** [SmartDataAnalytics/OpenResearch#164]
```
Exception: INSERT INTO Event (acronym,ordinal,homepage,title,startDate,endDate) values (:acronym,:ordinal,:homepage,:title,:startDate,:endDate)
failed:UNIQUE constraint failed: Event.acronym
record #281
```

**Comment by WolfgangFahl** [comment]
Non-Unique acronyms are just a special case and fortunately rare. They just need special attention because their is a risk if the disambiguation does not work.

**Comment by tholzheim** [comment]
|Acronym|Page Title|
|----|----|
|WWW 2011|[WWW 2014](https://www.openresearch.org/wiki/WWW_2014)|
|WWW 2011|[WWW 2011](https://www.openresearch.org/wiki/WWW_2011)|
|WWW 2011|[WWW 2013](https://www.openresearch.org/wiki/WWW_2013)|
|WCE 2011|[WCE 20112](https://www.openresearch.org/wiki/WCE_20112)|
|WCE 2011|[WCE 2011](https://www.openresearch.org/wiki/WCE_2011)|
|WACV 2017|[WACV 2017](https://www.openresearch.org/wiki/WACV_2017)|
|WACV 2017|[WACV 2017 : IEEE Winter Conference on Applications of Computer Vision](https://www.openresearch.org/wiki/WACV_2017_:_IEEE_Winter_Conference_on_Applications_of_Computer_Vision)|
|OpenSuCo @ SC 2017|[OpenSuCo2 2017](https://www.openresearch.org/wiki/OpenSuCo2_2017)|
|OpenSuCo @ SC 2017|[OpenSuCo @ SC 2017 : 2017 Workshop on Open Source Supercomputing (OpenSuCo-2017)](https://www.openresearch.org/wiki/OpenSuCo_@_SC_2017_:_2017_Workshop_on_Open_Source_Supercomputing_(OpenSuCo-2017))|
|JIST 2017|[JIST 2017](https://www.openresearch.org/wiki/JIST_2017)|
|JIST 2017|[JIST 2017 : 7th Joint International Semantic Technology Conference](https://www.openresearch.org/wiki/JIST_2017_:_7th_Joint_International_Semantic_Technology_Conference)|
|ICSC 2018|[ICSC 2018 : 12th IEEE International Conference on Semantic Computing (ICSC 2018)](https://www.openresearch.org/wiki/ICSC_2018_:_12th_IEEE_International_Conference_on_Semantic_Computing_(ICSC_2018))|
|ICSC 2018|[ICSC 2018](https://www.openresearch.org/wiki/ICSC_2018)|
|ICRE 2017|[ICRE 2017](https://www.openresearch.org/wiki/ICRE_2017)|
|ICRE 2017|[ICRE 2017 : 2017 3rd International Conference on Reliability Engineering (ICRE 2017)--SCOPUS, Ei Compendex](https://www.openresearch.org/wiki/ICRE_2017_:_2017_3rd_International_Conference_on_Reliability_Engineering_(ICRE_2017)--SCOPUS,_Ei_Compendex)|
|ICMLC 2018|[ICMLC 2018](https://www.openresearch.org/wiki/ICMLC_2018)|
|ICMLC 2018|[ICMLC 2018-2](https://www.openresearch.org/wiki/ICMLC_2018-2)|
|ICIS 2016|[ICIS 2016](https://www.openresearch.org/wiki/ICIS_2016)|
|ICIS 2016|[ICIS 20162](https://www.openresearch.org/wiki/ICIS_20162)|
|ICBSB 2017|[ICBSB 2017 : 2017 2nd International Conference on Biomedical Signal and Bioinformatics (ICBSB 2017)--Ei Compendex and Scopus](https://www.openresearch.org/wiki/ICBSB_2017_:_2017_2nd_International_Conference_on_Biomedical_Signal_and_Bioinformatics_(ICBSB_2017)--Ei_Compendex_and_Scopus)|
|ICBSB 2017|[ICBSB 2017](https://www.openresearch.org/wiki/ICBSB_2017)|
|HFR 2017|[HFR 2017 : 10th International Workshop on Human-Friendy Robotics (Springer SPAR Proceedings)](https://www.openresearch.org/wiki/HFR_2017_:_10th_International_Workshop_on_Human-Friendy_Robotics_(Springer_SPAR_Proceedings))|
|HFR 2017|[HFR 2017](https://www.openresearch.org/wiki/HFR_2017)|
|Gift-ACLA 2017|[Gift-ACLA 2017 : The Gift in Literature: ACLA Seminar](https://www.openresearch.org/wiki/Gift-ACLA_2017_:_The_Gift_in_Literature:_ACLA_Seminar)|
|Gift-ACLA 2017|[Gift-ACLA 2017](https://www.openresearch.org/wiki/Gift-ACLA_2017)|
|EDBT 2008|[EDBTW PhD 2008](https://www.openresearch.org/wiki/EDBTW_PhD_2008)|
|EDBT 2008|[EDBT 2008](https://www.openresearch.org/wiki/EDBT_2008)|
|3DUI 2020|[3dui 2010](https://www.openresearch.org/wiki/3dui_2010)|
|3DUI 2020|[3DUI 2020](https://www.openresearch.org/wiki/3DUI_2020)|

## Found with OpenRefine

1. Filter for duplicates
![step_1](https://user-images.githubusercontent.com/45004115/114590746-71491680-9c89-11eb-871c-8e49c8205b18.png)
2. Filter out empty acronyms
![step_2](https://user-images.githubusercontent.com/45004115/114591186-ec123180-9c89-11eb-9f9f-b5df4b897803.png)
3. Select duplicate and not empty values
![step_3](https://user-images.githubusercontent.com/45004115/114592017-c6d1f300-9c8a-11eb-8f20-6eaade27d494.png)

**Comment by WolfgangFahl** [comment]
How do we handle these with respect #168 ?
