### ISSUE TITLE
 WikiCFP provenance

### ISSUE THREAD

**Issue by MusaabKh** [SmartDataAnalytics/OpenResearch#166]
Some pages in openresearch  are imported from WikiCFP and marked with a text, "This CfP was obtained from ...". The pages are to be identified and the WikiCFP-ID is to be placed into the page with the source identifier. 
Example of such event: 
https://www.openresearch.org/mediawiki/index.php?title=AISB_2009

**Comment by WolfgangFahl** [comment]
See Task3 and # https://www.openresearch.org/wiki/Development_guidelines#Proposed_and_tested -n umber 3 WikiCFP should be an issue
## https://www.openresearch.org/mediawiki/index.php?title=AISB_2009
## https://www.openresearch.org/wiki/Property:WikiCFP-ID
## The idea is to add the source/provenance information and fix the content - first we need the quick and easy solution - no fiddling with complicate stuff like location data. Simply match the eventId found against the sqllite database

**Comment by WolfgangFahl** [comment]
Identify data imported from WikiCFP and mark it with the WikiCFP-ID

**Comment by WolfgangFahl** [comment]
use bots like wikipush, wikiedit, wikinuke, wikiupload, wikuser to do mass changes of pages e.g. adding the source "WikiCfP" information to pages imported from WikiCfp

 This CfP was obtained from [http://www.wikicfp.com/cfp/servlet/event.showcfp?eventid=3864&copyownerid=2 WikiCFP]

=>

[[Source::wikicfp]][[eventId::3864]]

=>

{{Event|...|Source=wikicfp|eventId=3864| ...}}

**Comment by WolfgangFahl** [comment]
This is going to be a nice OpenRefine example for the upcoming weeks. Right now we just want to import the WikiCFP entries to orintegrate to show that the principle works.

**Comment by WolfgangFahl** [comment]
see 
```bash
root@confident:/home/wf/.ptp# ls -l
total 170496
-rw-r--r-- 1 wf www-data 174587904 Feb 10 08:06 Event_all.db
```

**Comment by MusaabKh** [comment]
Sample Extraction of WikiCFP-ID using a python snippet and wikirestore: 
https://confident.dbis.rwth-aachen.de/ormk/index.php?title=AISB_2009&type=revision&diff=19307&oldid=17526

**Comment by WolfgangFahl** [comment]
see https://confident.dbis.rwth-aachen.de/or/index.php/Template:EventSeriesOverview

**Comment by WolfgangFahl** [comment]
The API for "modify property x of page y using topic t to value v" should be used for this.

**Comment by tholzheim** [comment]
Applied fixer to orclone resulting in 2459 wikicfpIds being added to the events.
See https://confident.dbis.rwth-aachen.de/or/index.php?title=Property:WikiCFP-ID

**Comment by WolfgangFahl** [comment]
Great - can we close this ticke now?

**Comment by tholzheim** [comment]
Yes, for all events that have the wikicfp id in the freetext the wikicfpId property has been set
