### ISSUE TITLE
Captcha nicht korrekt angezeigt 

### ISSUE THREAD

**Issue by An-ette** [SmartDataAnalytics/OpenResearch#189]
Ich habe versucht, im Klon die "IEEE VPPC 2021" anzulegen. Dabei gab es Probleme mit dem Captcha, das nicht korrekt angezeigt wurde (da ich die URL zur Homepage der Veranstaltung angeben wollte). Das Anlegen der Veranstaltung hat erst geklappt, als ich die URL entfernt habe.

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/115722920-bd7a1200-a37f-11eb-966e-5875e6c36217.png)

**Comment by WolfgangFahl** [comment]
Part of #186

**Comment by WolfgangFahl** [comment]
https://confident.dbis.rwth-aachen.de/or/index.php/ConfirmEdit is being used with a recaptcha key which is domain bound. As a work around i could set your user to be e-mail confirmed manually.

**Comment by WolfgangFahl** [comment]
There are multiple options to handle this:

- Generate a recaptcha key for the clone
- use a different captcha method
- set the e-mail confirmation timestamp manually in the database

**Comment by WolfgangFahl** [comment]
Closing while workarounds are active. Please reopen when needed
