### ISSUE TITLE
Need to set time via Internet on RWTH i5 ConfIDent server

### ISSUE THREAD

**Issue by WolfgangFahl** [SmartDataAnalytics/OpenResearch#201]
the time is off by 2 1/2 minutes already which is enough to make synchronizations with wikipush fail due to wrong timestamps.

**Comment by WolfgangFahl** [comment]
https://serverfault.com/questions/1024770/ubuntu-20-04-time-sync-problems-and-possibly-incorrect-status-information

**Comment by WolfgangFahl** [comment]
```
sudo apt-get install systemd-timesyncd 
```

**Comment by WolfgangFahl** [comment]
https://askubuntu.com/a/1163409/129227 needed?

**Comment by RLinde-i5** [comment]
Initial time service config had wrong entry AND external timeservers no longer supported at RWTH. 
Configured /etc/systemd/timesyncd.conf to use timeserver.rwth-aachen.de

**Comment by WolfgangFahl** [comment]
@RLinde-i5
