### ISSUE TITLE
Empty date values are displayed (incorrect) in series

### ISSUE THREAD

**Issue by hauschke** [SmartDataAnalytics/OpenResearch#218]
![grafik](https://user-images.githubusercontent.com/1275231/116066458-61b5ce80-a688-11eb-8304-f6bae9a96d36.png)

If day and month are not given it's displayed as Jan 1st in the connected series.

**Comment by WolfgangFahl** [comment]
see https://confident.dbis.rwth-aachen.de/or/index.php?title=FABRICATE_2011&type=revision&diff=231688&oldid=231687
for the working way to do this. We just don't have the UI yet.
