### ISSUE TITLE
External Spreadsheet editing for Event Series

### ISSUE THREAD

**Issue by WolfgangFahl** [SmartDataAnalytics/OpenResearch#236]
see #230

**Comment by tholzheim** [comment]
Situation: Event Series 3DUI is given
Action: Edit it with an external csv editor
Expected result: Corresponding Event pages such as 3DUI 2014 and 3DUI 2020 are changed. New pages created if needed

Possible csv output:
```csv
State,Country,Ordinal,End date,Submission deadline,pageTitle,Acronym,Series,has Proceedings Link,Start date,Homepage,Type,City,Title 
South Carolina,USA,,2016/03/20,,3DUI 2016,3DUI 2016,3DUI,,2016/03/19,,Conference,Greenville,IEEE Symposium on 3D User Interfaces 
,USA,,2020/03/26,2019/09/03,3DUI 2020,3DUI 2020,3DUI,,2020/03/22,http://ieeevr.org/2020/,Symposium,Atlanta,IEEE Symposium on 3D User Interfaces 
,USA,15,2010/03/21,,3dui 2010,3DUI 2020,3DUI,https://www.computer.org/csdl/proceedings/3dui/2010/12OmNAsTgX7,2010/03/20,http://ieeevr.org/2020/,Symposium,Waltham,IEEE Symposium on 3D User Interfaces 
```

**Comment by tholzheim** [comment]
![op_export_import](https://user-images.githubusercontent.com/45004115/120501111-a3414400-c3c1-11eb-82f0-6dd6258884ec.png)

**Comment by WolfgangFahl** [comment]
see https://rq.bitplan.com/index.php/Workdocumentation_2021-06-30_TH#Try_CSV_import_.26_export

**Comment by WolfgangFahl** [comment]
The csv separator used is currently ",". That is not recognized as the default separator in some environments. See https://superuser.com/questions/606272/how-to-get-excel-to-interpret-the-comma-as-a-default-delimiter-in-csv-files

We'll need an option e.g. to specify the separator.

**Comment by MusaabKh** [comment]
Further developments: https://rq.bitplan.com/index.php/Workdocumentation_2021-07-09_MK#CSV_Generation

**Comment by WolfgangFahl** [comment]
Past CSV exports have  created broken results such as:
https://www.openresearch.org/mediawiki/index.php?title=BTU_2020&action=history

**Comment by WolfgangFahl** [comment]
Use https://github.com/WolfgangFahl/ConferenceCorpus/issues/10 as a service

**Comment by MusaabKh** [comment]
When we create the csv, the separator and locality is taken into account. 
The locality consists of two things; The country and the language.
Default locality: DE, Germany, EN, USA.
Far away from the standardized ISO version.
Internationalization issue involves column of type dates and floating points.
The columns need to survive the round trip in the same shape.
When we get the data back it is not ruined.

**Comment by WolfgangFahl** [comment]
The base functionality is available now so closing this ticket. Please file new issues if there any problems in detail.
