### ISSUE TITLE
Better forms

### ISSUE THREAD

**Issue by tholzheim** [SmartDataAnalytics/OpenResearch#24]
Requirement:
* https://rq.bitplan.com/index.php/Enter_Event
Example:
* https://www.openresearch.org/wiki/SAGT_2020

**Comment by tholzheim** [comment]
Better then this: https://or.bitplan.com/index.php/SAGT_2020

**Comment by MusaabKh** [comment]
Event Series SAGT : https://www.openresearch.org/wiki/SAGT

**Comment by Julian-tib** [comment]
Current Version of the high fidelity Wireframe for the forms: https://fuutxr.axshare.com 
Some properties included here could still be left out for the first version.

**Comment by WolfgangFahl** [comment]
Not part of this project anymore.
