### ISSUE TITLE
Command Line for EventFixer

### ISSUE THREAD

**Issue by WolfgangFahl** [SmartDataAnalytics/OpenResearch#242]
we'd like to integrate the event fixer in to the procedure of "get your own copy of Openresearch"

Currently the state of affairs is:
```
python eventFixer.py -h
usage: eventFixer.py [-h] [-d] [-V] [-l] -s SOURCE -pr PAINRATING
                     [-fn FIXERNAMES [FIXERNAMES ...]]

eventfix

      Created by Musaab Khan on 2020-10-31.
    

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           set debug level [default: False]
  -V, --version         show program's version number and exit
  -l, --login           login to source wiki for access permission
  -s SOURCE, --source SOURCE
                        source wiki id
  -pr PAINRATING, --painRating PAINRATING
                        give the painrating number for events to get under
  -fn FIXERNAMES [FIXERNAMES ...], --fixerNames FIXERNAMES [FIXERNAMES ...]
                        List of fixers to check for rating

```

**Comment by WolfgangFahl** [comment]
first fixer go get working is the one for #166 which is pretty much a simple wikiedit call

**Comment by MusaabKh** [comment]
Currently a basic implementation of returning events over a certain pain rating threshold.
https://rq.bitplan.com/index.php/Workdocumentation_2021-07-08_MK#Event_Fixers_Command_Line_interface

**Comment by MusaabKh** [comment]
A fixer(WikiCFPID fixer) has been integrated into the command line. Can be tested. I am currently testing it with getYourOwnCopyOfOpenResearch.
Documentation: https://rq.bitplan.com/index.php/Workdocumentation_2021-07-08_MK#Help_of_eventfix

**Comment by WolfgangFahl** [comment]
There is a new release 0.0.23 https://pypi.org/project/OpenResearchMigration/ and I am running a docker image with it now see https://rq.bitplan.com/index.php/Workdocumentation_2021-07-09

**Comment by WolfgangFahl** [comment]
Fixers with command line are available now for

- #119
- #136 
- #150 
- #152 
-
