### ISSUE TITLE
Add contributionType to all Event and EventSeries Pages

### ISSUE THREAD

**Issue by tholzheim** [SmartDataAnalytics/OpenResearch#271]
- [x] Add [ContributionType](https://confident.dbis.rwth-aachen.de/or/index.php?title=Property:ContributionType) property
- [x] Assign contribution type to all event and event series pages
  - 1 if page is from legit organizer/user
  - 2 if page is from spammer

**Comment by tholzheim** [comment]
314 Pages were flaged as [Spam Pages](https://confident.dbis.rwth-aachen.de/or/index.php?title=Spam_Pages)

**Comment by Julian-tib** [comment]
Thank you for the fast addidtion of this property!

Unfortunately 25 EventSeries that were originally created by dubious accounts (contribution type=2) were completed by curators: https://confident.dbis.rwth-aachen.de/or/index.php?title=Event_Series_For_Confident:

I will manually change the contribution type of the corresponding events and of the eventseries themselves. Hence, no work from your side is required. This is only ment to inform you and keep a record of this manual change.

`<html><body>


  | Event Series Contribution Type | Event Contribution Types ⠉ | Event
-- | -- | -- | --
ACCC | 1 | 12 | ACCC 2020ACCC 2021
ACCSE | 1 | 2 | ACCSE 2021
ACEE | 1 | 2 | ACEE 2021
ACHI | 1 | 1112 | ACHI 2021ACHI 2008ACHI 2019ACHI 2020
ACMME | 1 | 121111111 | ACMME 2013ACMME 2021ACMME 2014ACMME 2015ACMME 2019ACMME 2017ACMME 2020ACMME 2018ACMME 2016
ADAPTIVE | 1 | 11211 | ADAPTIVE 2017ADAPTIVE 2020ADAPTIVE 2021ADAPTIVE 2018ADAPTIVE 2019
ADIP | 1 | 121 | ADIP 2019ADIP 2021ADIP 2020
AEEES | 1 | 2 | AEEES 2021
AFIN | 1 | 121 | AFIN 2021AFIN 2020AFIN 2009
AHMIS | 1 | 21 | AHMIS 2021AHMIS 2020
AICCC | 1 | 1211 | AICCC 2018AICCC 2021AICCC 2020AICCC 2019
AITC | 1 | 112 | AITC 2020AITC 2019AITC 2021
AIVR | 1 | 1112 | AIVR 2019AIVR 2020AIVR 2018AIVR 2021
ALLDATA | 1 | 121 | ALLDATA 2019ALLDATA 2021ALLDATA 2020
ALLSENSORS | 1 | 21 | ALLSENSORS 2020ALLSENSORS 2021
AMBIENT | 1 | 112 | AMBIENT 2021AMBIENT 2019AMBIENT 2020
BDAI | 1 | 2 | BDAI 2021
CENTRIC | 1 | 1211 | CENTRIC 2021CENTRIC 2020CENTRIC 2018CENTRIC 2019
COLLA | 1 | 2111 | COLLA 2020COLLA 2018COLLA 2021COLLA 2019
EREE | 1 | 2111 | EREE 2021EREE 2022EREE 2020EREE 2019
FASSI | 1 | 21111111 | FASSI 2020FASSI 2021FASSI 2019FASSI 2018FASSI 2017FASSI 2016FASSI 2015FASSI 2022
FUTURE COMPUTING | 1 | 21111111111111 | FUTURE COMPUTING 2021FUTURE COMPUTING 2017FUTURE COMPUTING 2022FUTURE COMPUTING 2020FUTURE COMPUTING 2019FUTURE COMPUTING 2018FUTURE COMPUTING 2016FUTURE COMPUTING 2015FUTURE COMPUTING 2009FUTURE COMPUTING 2010FUTURE COMPUTING 2011FUTURE COMPUTING 2012FUTURE COMPUTING 2013FUTURE COMPUTING 2014
HUSO | 1 | 112 | HUSO 2021HUSO 2022HUSO 2020
ICDTE | 1 | 2 | ICDTE 2021
VPPC | 1 | 1112 | VPPC 2009VPPC 2008VPPC 09VPPC 2021


</body>
</html>[Event Series Contribution Type](https://confident.dbis.rwth-aachen.de/or/index.php?title=Property:ContributionType)	[Event Contribution Types](https://confident.dbis.rwth-aachen.de/or/index.php?title=Property:ContributionType) ⠉	[Event](https://confident.dbis.rwth-aachen.de/or/index.php?title=Property:Event_in_series)
[ACCC](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACCC)	1	1
2	[ACCC 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACCC_2020)
[ACCC 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACCC_2021)
[ACCSE](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACCSE)	1	2	[ACCSE 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACCSE_2021)
[ACEE](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACEE)	1	2	[ACEE 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACEE_2021)
[ACHI](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACHI)	1	1
1
1
2	[ACHI 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACHI_2021)
[ACHI 2008](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACHI_2008)
[ACHI 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACHI_2019)
[ACHI 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACHI_2020)
[ACMME](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME)	1	1
2
1
1
1
1
1
1
1	[ACMME 2013](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2013)
[ACMME 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2021)
[ACMME 2014](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2014)
[ACMME 2015](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2015)
[ACMME 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2019)
[ACMME 2017](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2017)
[ACMME 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2020)
[ACMME 2018](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2018)
[ACMME 2016](https://confident.dbis.rwth-aachen.de/or/index.php?title=ACMME_2016)
[ADAPTIVE](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADAPTIVE)	1	1
1
2
1
1	[ADAPTIVE 2017](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADAPTIVE_2017)
[ADAPTIVE 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADAPTIVE_2020)
[ADAPTIVE 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADAPTIVE_2021)
[ADAPTIVE 2018](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADAPTIVE_2018)
[ADAPTIVE 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADAPTIVE_2019)
[ADIP](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADIP)	1	1
2
1	[ADIP 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADIP_2019)
[ADIP 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADIP_2021)
[ADIP 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=ADIP_2020)
[AEEES](https://confident.dbis.rwth-aachen.de/or/index.php?title=AEEES)	1	2	[AEEES 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=AEEES_2021)
[AFIN](https://confident.dbis.rwth-aachen.de/or/index.php?title=AFIN)	1	1
2
1	[AFIN 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=AFIN_2021)
[AFIN 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=AFIN_2020)
[AFIN 2009](https://confident.dbis.rwth-aachen.de/or/index.php?title=AFIN_2009)
[AHMIS](https://confident.dbis.rwth-aachen.de/or/index.php?title=AHMIS)	1	2
1	[AHMIS 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=AHMIS_2021)
[AHMIS 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=AHMIS_2020)
[AICCC](https://confident.dbis.rwth-aachen.de/or/index.php?title=AICCC)	1	1
2
1
1	[AICCC 2018](https://confident.dbis.rwth-aachen.de/or/index.php?title=AICCC_2018)
[AICCC 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=AICCC_2021)
[AICCC 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=AICCC_2020)
[AICCC 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=AICCC_2019)
[AITC](https://confident.dbis.rwth-aachen.de/or/index.php?title=AITC)	1	1
1
2	[AITC 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=AITC_2020)
[AITC 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=AITC_2019)
[AITC 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=AITC_2021)
[AIVR](https://confident.dbis.rwth-aachen.de/or/index.php?title=AIVR)	1	1
1
1
2	[AIVR 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=AIVR_2019)
[AIVR 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=AIVR_2020)
[AIVR 2018](https://confident.dbis.rwth-aachen.de/or/index.php?title=AIVR_2018)
[AIVR 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=AIVR_2021)
[ALLDATA](https://confident.dbis.rwth-aachen.de/or/index.php?title=ALLDATA)	1	1
2
1	[ALLDATA 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=ALLDATA_2019)
[ALLDATA 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ALLDATA_2021)
[ALLDATA 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=ALLDATA_2020)
[ALLSENSORS](https://confident.dbis.rwth-aachen.de/or/index.php?title=ALLSENSORS)	1	2
1	[ALLSENSORS 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=ALLSENSORS_2020)
[ALLSENSORS 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ALLSENSORS_2021)
[AMBIENT](https://confident.dbis.rwth-aachen.de/or/index.php?title=AMBIENT)	1	1
1
2	[AMBIENT 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=AMBIENT_2021)
[AMBIENT 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=AMBIENT_2019)
[AMBIENT 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=AMBIENT_2020)
[BDAI](https://confident.dbis.rwth-aachen.de/or/index.php?title=BDAI)	1	2	[BDAI 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=BDAI_2021)
[CENTRIC](https://confident.dbis.rwth-aachen.de/or/index.php?title=CENTRIC)	1	1
2
1
1	[CENTRIC 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=CENTRIC_2021)
[CENTRIC 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=CENTRIC_2020)
[CENTRIC 2018](https://confident.dbis.rwth-aachen.de/or/index.php?title=CENTRIC_2018)
[CENTRIC 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=CENTRIC_2019)
[COLLA](https://confident.dbis.rwth-aachen.de/or/index.php?title=COLLA)	1	2
1
1
1	[COLLA 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=COLLA_2020)
[COLLA 2018](https://confident.dbis.rwth-aachen.de/or/index.php?title=COLLA_2018)
[COLLA 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=COLLA_2021)
[COLLA 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=COLLA_2019)
[EREE](https://confident.dbis.rwth-aachen.de/or/index.php?title=EREE)	1	2
1
1
1	[EREE 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=EREE_2021)
[EREE 2022](https://confident.dbis.rwth-aachen.de/or/index.php?title=EREE_2022)
[EREE 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=EREE_2020)
[EREE 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=EREE_2019)
[FASSI](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI)	1	2
1
1
1
1
1
1
1	[FASSI 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI_2020)
[FASSI 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI_2021)
[FASSI 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI_2019)
[FASSI 2018](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI_2018)
[FASSI 2017](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI_2017)
[FASSI 2016](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI_2016)
[FASSI 2015](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI_2015)
[FASSI 2022](https://confident.dbis.rwth-aachen.de/or/index.php?title=FASSI_2022)
[FUTURE COMPUTING](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING)	1	2
1
1
1
1
1
1
1
1
1
1
1
1
1	[FUTURE COMPUTING 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2021)
[FUTURE COMPUTING 2017](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2017)
[FUTURE COMPUTING 2022](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2022)
[FUTURE COMPUTING 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2020)
[FUTURE COMPUTING 2019](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2019)
[FUTURE COMPUTING 2018](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2018)
[FUTURE COMPUTING 2016](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2016)
[FUTURE COMPUTING 2015](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2015)
[FUTURE COMPUTING 2009](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2009)
[FUTURE COMPUTING 2010](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2010)
[FUTURE COMPUTING 2011](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2011)
[FUTURE COMPUTING 2012](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2012)
[FUTURE COMPUTING 2013](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2013)
[FUTURE COMPUTING 2014](https://confident.dbis.rwth-aachen.de/or/index.php?title=FUTURE_COMPUTING_2014)
[HUSO](https://confident.dbis.rwth-aachen.de/or/index.php?title=HUSO)	1	1
1
2	[HUSO 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=HUSO_2021)
[HUSO 2022](https://confident.dbis.rwth-aachen.de/or/index.php?title=HUSO_2022)
[HUSO 2020](https://confident.dbis.rwth-aachen.de/or/index.php?title=HUSO_2020)
[ICDTE](https://confident.dbis.rwth-aachen.de/or/index.php?title=ICDTE)	1	2	[ICDTE 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=ICDTE_2021)
[VPPC](https://confident.dbis.rwth-aachen.de/or/index.php?title=VPPC)	1	1
1
1
2	[VPPC 2009](https://confident.dbis.rwth-aachen.de/or/index.php?title=VPPC_2009)
[VPPC 2008](https://confident.dbis.rwth-aachen.de/or/index.php?title=VPPC_2008)
[VPPC 09](https://confident.dbis.rwth-aachen.de/or/index.php?title=VPPC_09)
[VPPC 2021](https://confident.dbis.rwth-aachen.de/or/index.php?title=VPPC_2021)`
