### ISSUE TITLE
Create new Has_CORE_Rank property

### ISSUE THREAD

**Issue by mattia-lecci** [SmartDataAnalytics/OpenResearch#278]
The only CORE ranks present in openresearch.org are from 2014, 2017, and 2018 (see [here](https://www.openresearch.org/wiki/Property:Has_CORE_Rank)), which are outdated.
The latest one, as of august 2023, is from 2021 (see [here](http://portal.core.edu.au/conf-ranks/)).

I could not find an instruction page on how to create a new related property, but tried to the [Create a property](https://www.openresearch.org/wiki/Special:CreateProperty) page.
The page was then edited to `#REDIRECT [[Property:Has CORE Rank]]`, like the others.
The CORE 2021 rank does appear in the list of synonims of the Has_CORE_Rank property, but it seems that I cannot use it in event series.

This is related to #254, where it is not clear whether more ranks should be added at all.

## Use case
Some ranks changed, e.g., [WoWMoM](http://portal.core.edu.au/conf-ranks/691/) was downgraded from A to B.

Adding the property `|has CORE2021 Rank=B` to [WoWMoM](https://www.openresearch.org/wiki/WoWMoM) does not show any CORE rank.
Adding both 
```
|has CORE2021 Rank=B
|has CORE2018 Rank=A
```
only shows the CORE2018 rank, which is not correct anymore.

**Comment by mattia-lecci** [comment]
Dear Wolfgang, is there any documentation on this that i might have missed?
I could try to fix the problem myself or propose a solution for you to evaluate.

The current solution clearly does not work, any suggestion on how to fix it or a procedure on how CORE ranks from 2014, 2017, and 2018 were made would be extremely helpful!

**Comment by WolfgangFahl** [comment]
@mattia-lecci  - the Event_series template would have to be fixed:
https://www.openresearch.org/mediawiki/index.php?title=Template:Event_series&action=edit

We stopped the work on OpenResearch over a year ago. All issues are more or less in a "won't fix" state as of now.
You might want to look into https://www.confident-conference.org/index.php/Main_Page which is more current than this project.

**Comment by mattia-lecci** [comment]
Thank you, the page now works as expected!

I wasn't aware of confident-conference.org, thank you for the pointer, i'll look into that as well!
