### ISSUE TITLE
improve refreshing of properties by calling runJobs from crontab entry every minute

### ISSUE THREAD

**Issue by WolfgangFahl** [SmartDataAnalytics/OpenResearch#38]
openresearch22 server does not have the needed crontab entry (or does it?)

**Comment by WolfgangFahl** [comment]
watch out for https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4883

**Comment by Nikerabbit** [comment]
There are some tips in https://www.mediawiki.org/wiki/Manual:Job_queue#Set_up - namely about avoiding running too many runJobs scripts concurrently. Personally I prefer to use a service.

**Comment by WolfgangFahl** [comment]
@Nikerabbit  thank you for pointing this out. In my families i to a pgrep protection like below. Unfortunately OpenResearch is not yet part of such a family
```
#!/bin/bash
# WF 2015-06-08
# run jobs for all sites
jobs=$(pgrep -fla runjobs | wc -l)
if [ $jobs -gt 3 ]
then
  echo "$jobs runjobs already running ..."
  exit 1
fi
cd /srv/www/mediawiki/code
host=$(hostname)
cat $host.sites | egrep -v "^#"  | while read siteid site
do
  #./update $siteid
  #echo $siteid
  #echo $site
  /usr/bin/php /srv/www/mediawiki/code/worksite.php $site runJobs \
  --conf /srv/www/mediawiki/sites/$site/FullLocalSettings.php >> /var/log/mediawiki/runJobs_$siteid.log 2>&1
done

```

**Comment by WolfgangFahl** [comment]
Theoretically this could be fixed with a crontab entry. The overruning process issues will be an immediate follow up problem due to #72 given that a single property change might need to a rebuild time of the triple store of some 5 h.
<img width="431" alt="grafik" src="https://user-images.githubusercontent.com/1336221/115103468-6674d700-9f52-11eb-8ffd-76cef2d0e31e.png">

**Comment by WolfgangFahl** [comment]
works on or35.
```
wf@confident:/var/log/mediawiki$ tail -f runJobs_or35.log 
--------------------------------------
Running runJobs.php for or35
--------------------------------------
2021-04-23 16:30:02 smw.propertyStatisticsRebuild SMW\SQLStore\Installer rootJobIsSelf=1 rootJobSignature=db42ba0748fde875c7dd60ebc4ffd96d265c3390 rootJobTimestamp=20210423154104 waitOnCommandLine=10 namespace=0 title=SMW\SQLStore\Installer requestId=3e0ddb2aedfe4a0f0a304f80 (id=200184,timestamp=20210423162135) STARTING

```
Might need to reopen later in final TIB infrastructure
