### ISSUE TITLE
automate uploaded files to http://mwcsvimport.pronique.com/ are empty

### ISSUE THREAD

**Issue by liyakun** [SmartDataAnalytics/OpenResearch#6]
The script [upload_csv.py](https://github.com/EIS-Bonn/OpenResearch/blob/master/wikiCFP/upload_csv.py) uploads csv files to [mwcsvimport](http://mwcsvimport.pronique.com/), but the uploaded files are empty. I cannot figure out where the problem happens, it would be great if anyone can help, thanks.

(In addition: the "upload_csv" function in  [upload_csv.py](https://github.com/EIS-Bonn/OpenResearch/blob/master/wikiCFP/upload_csv.py) uploads the file, and there is also a function "login" to keep the login session)

**Comment by WolfgangFahl** [comment]
see https://github.com/WolfgangFahl/ProceedingsTitleParser/issues/33 which makes this obsolete. See https://confident.dbis.rwth-aachen.de/dblpconf/sample/ptp/Event_wikicfp/1000 for a current sample
