### ISSUE TITLE
openresarch.org copy shows SemanticMediaWiki upgrade key error

### ISSUE THREAD

**Issue by WolfgangFahl** [SmartDataAnalytics/OpenResearch#78]
https://wiki.tib.eu/jira/browse/CONFIDENT-113

 Wolfgang Fahl hat einen Kommentar hinzugefügt - 13.06.2020 16:19

As a workaround instead of setting https://www.semantic-mediawiki.org/wiki/Help:$smwgConfigFileDir as suggested in the issue i called php extensions/SemanticMediaWiki/maintenance/setupStore.php and made sure LocalSettings.php choose "localhost" as the configuration in this case. To point to the "correct" target wiki in the family a symbolic link in /var/www/mediawiki/sites is necessary that will point to the server that needs to be configured. In the example below the "or" OpenResearch.org copy wiki is the target. This only holds true for the command line - in the access by server case the target family member is selected by port which is a hard code switch statement.

root@confident22:/var/www/mediawiki/sites# ls -l
total 20
-rw-r--r-- 1 wf wf 5458 Jun 13 12:05 ConfIDentSettings.php
lrwxrwxrwx 1 root root 2 Jun 13 14:24 localhost -> or
drwxrwxr-x 3 www-data www-data 4096 Jun 13 14:27 or
drwxrwxr-x 3 www-data www-data 4096 Jun 13 14:28 rq
drwxr-xr-x 2 www-data www-data 4096 Jun 13 14:28 wiki

Permalink Bearbeiten Löschen
wfahl Wolfgang Fahl hat einen Kommentar hinzugefügt - 28.07.2020 16:50

Trying different settings now
Permalink Bearbeiten Löschen
wfahl Wolfgang Fahl hat einen Kommentar hinzugefügt - 03.08.2020 11:25

see workaround in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4785 - will hit us again on any upgrade if not fixed upstream.

**Comment by Seppeltronics** [comment]
Hello @WolfgangFahl ,

it seems as I have the same issue:

Semantic MediaWiki: 3.2.3 (smw:2020-04-18)
MediaWiki:1.35.2

Not sure how it relates to https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4785

I can not understand why that installetion does not work out of the Box on my Ionos machine and why useres have to bother with something like this at all, https://www.semantic-mediawiki.org/wiki/Help:Upgrade_key , it is really hard to understand either.

Could you may write a summary and provide the files that need to be replaced, if possible? I's really like to fix and work with it. Any help would be really great, beacause I'd relly like to try the Semantics-Extension, it seems to be a really good extension that is very nice.

Thank you very much in advance.

Best Regards, Seppel

**Comment by WolfgangFahl** [comment]
@Seppeltronics  Just provided the pull request which also has the changes.

**Comment by WolfgangFahl** [comment]
Closing this for the time being since it doesn't hit us when using https://pypi.org/project/pymediawikidocker/
