### ISSUE TITLE
Unclear "Submission/Acceptance" chart

### ISSUE THREAD

**Issue by mnmami** [SmartDataAnalytics/OpenResearch#8]
In the conference page, when we have so many entires, the chart "Submission/Acceptance" starts to be unclear.
This is an example: https://www.openresearch.org/wiki/SIGMOD
![grafik](https://user-images.githubusercontent.com/1336221/108075688-eeca1f00-706a-11eb-92c7-994b9819d58c.png)

with comparison to this: https://www.openresearch.org/wiki/EKAW
![grafik](https://user-images.githubusercontent.com/1336221/108075766-05707600-706b-11eb-96d5-00f2a5c92988.png)

**Comment by liyakun** [comment]
@mnmami the values are stacked together for each entry, this looks more clear than before.

**Comment by mnmami** [comment]
Indeed it's more clear now, but the blue bars are not always labeled with the number of submissions.

**Comment by liyakun** [comment]
@mnmami actually the blue bars are labeled but not visible in the plot. I did not find method to adjust the previous view to show all the values. Instead, I changed the view and moved the legend outside of the chart. It looks fine now, but still has possibility to be messy when there are many events in the series.
